site: Salvatore Cordiano
url: https://cordiano.com
title: Salvatore Cordiano
description: Engineering Manager
twitter:
  username: parallelit
  card: summary
  creator: parallelit
author:
  twitter: parallelit
  name: Salvatore Cordiano
  avatar:
  email: salvatore@cordiano.it
  url: https://cordiano.com
permalink: pretty
destination: ./docs

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  - .idea
  - Makefile
  - README.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
